version: "3.8"

services:
    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastapi_app
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - PYTHONUNBUFFERED=1
        command:
            [
                "poetry",
                "run",
                "uvicorn",
                "api:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
            ]

    streamlit:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: streamlit_app
        ports:
            - "8501:8501"
        depends_on:
            - fastapi
        volumes:
            - .:/app
        environment:
            - PYTHONUNBUFFERED=1
            - GEMINI_API_KEY=${GEMINI_API_KEY}
        command:
            [
                "poetry",
                "run",
                "streamlit",
                "run",
                "app.py",
                "--server.headless=true",
                "--server.port=8501",
                "--server.enableCORS=false",
            ]
